# Generated by Django 6.1 on 2026-08-27 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AROLOptimizationRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('IMAGE_COMPRESSION', 'Image Compression'), ('METADATA_STRIPPING', 'Metadata Stripping'), ('PROMPT_OPTIMIZATION', 'Prompt Optimization'), ('RESPONSE_CACHING', 'Response Caching'), ('BATCH_PROCESSING', 'Batch Processing')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('times_applied', models.IntegerField(default=0)),
                ('total_savings_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('VISION', 'Vision Analysis'), ('TEXT', 'Text Analysis'), ('VOICE', 'Voice Analysis'), ('GENERATION', 'Content Generation')], max_length=20)),
                ('original_input_size_bytes', models.IntegerField()),
                ('optimized_input_size_bytes', models.IntegerField()),
                ('input_reduction_percentage', models.FloatField()),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('cache_key', models.CharField(blank=True, max_length=64)),
                ('preprocessing_time_ms', models.IntegerField()),
                ('api_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('total_time_ms', models.IntegerField()),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('savings_vs_baseline_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_type', 'created_at'], name='arol_airequ_request_c8c1ee_idx'), models.Index(fields=['cache_hit'], name='arol_airequ_cache_h_c49443_idx')],
            },
        ),
        migrations.CreateModel(
            name='AROLDashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_type', models.CharField(max_length=20)),
                ('total_requests', models.IntegerField()),
                ('vision_requests', models.IntegerField()),
                ('text_requests', models.IntegerField()),
                ('voice_requests', models.IntegerField()),
                ('generation_requests', models.IntegerField()),
                ('avg_input_reduction_percent', models.FloatField()),
                ('total_data_saved_mb', models.FloatField()),
                ('cache_hit_rate', models.FloatField()),
                ('avg_response_time_ms', models.FloatField()),
                ('avg_preprocessing_time_ms', models.FloatField()),
                ('total_estimated_cost_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_savings_vs_baseline_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('savings_percentage', models.FloatField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('period_start', 'period_type')},
            },
        ),
    ]
