# Generated by Django 6.1 on 2026-08-27 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_reference', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('user_requirements', models.JSONField(default=dict)),
                ('business_case', models.JSONField(default=dict)),
                ('project_initiation_document', models.JSONField(default=dict)),
                ('project_plan', models.JSONField(default=dict)),
                ('resource_plan', models.JSONField(default=dict)),
                ('risk_register', models.JSONField(default=list)),
                ('quality_plan', models.JSONField(default=dict)),
                ('sv_targets', models.JSONField(default=dict)),
                ('evaluation_plan', models.JSONField(default=dict)),
                ('current_stage', models.CharField(choices=[('INITIATION', 'Initiation'), ('PLANNING', 'Planning'), ('EXECUTION', 'Execution'), ('MONITORING', 'Monitoring & Control'), ('CLOSURE', 'Closure')], default='INITIATION', max_length=20)),
                ('approval_status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('generated_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.generatedactivity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('SMALL', 'Small Project'), ('MEDIUM', 'Medium Project'), ('LARGE', 'Major Project'), ('PROGRAMME', 'Programme')], max_length=15)),
                ('business_case_template', models.JSONField(default=dict)),
                ('project_initiation_document', models.JSONField(default=dict)),
                ('project_plan_template', models.JSONField(default=dict)),
                ('risk_register_template', models.JSONField(default=dict)),
                ('sv_requirements_section', models.TextField()),
                ('evaluation_framework', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
