# Generated by Django 6.1 on 2026-08-20 17:27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProxy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('EMPLOYMENT', 'Employment & Skills'), ('HEALTH', 'Health & Wellbeing'), ('COMMUNITY', 'Community Cohesion'), ('ENVIRONMENT', 'Environmental'), ('DIGITAL', 'Digital Inclusion'), ('HOUSING', 'Housing Stability')], max_length=20)),
                ('outcome_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('financial_value_gbp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_basis', models.TextField()),
                ('confidence_interval', models.JSONField(default=dict)),
                ('validity_period_years', models.IntegerField(default=3)),
                ('surrey_hwb_alignment', models.BooleanField(default=False)),
                ('nhs_business_recommendation', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Financial Proxies',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('intervention_type', models.CharField(choices=[('PREVENTATIVE', 'Preventative Service'), ('TREATMENT', 'Treatment Service'), ('COMMUNITY', 'Community Development'), ('DIGITAL', 'Digital Inclusion'), ('EMPLOYMENT', 'Employment Support')], max_length=20)),
                ('target_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_breakdown', models.JSONField(default=dict)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('evaluation_status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('EVALUATED', 'Evaluated')], default='PLANNED', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_communities', models.ManyToManyField(related_name='interventions', to='communities.communityprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('measurement_method', models.TextField()),
                ('evidence_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list)),
                ('verified_by', models.CharField(blank=True, max_length=200)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('deadweight', models.FloatField(default=0.0)),
                ('displacement', models.FloatField(default=0.0)),
                ('attribution', models.FloatField(default=1.0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financial_proxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='impact.financialproxy')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='impact.intervention')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredictiveResourceOptimizer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intervention_type', models.CharField(max_length=50)),
                ('projected_outcomes', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField()),
                ('similar_interventions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('recommended_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('optimal_targeting', models.JSONField(default=dict)),
                ('expected_sroi', models.FloatField(null=True)),
                ('actual_outcomes', models.JSONField(blank=True, null=True)),
                ('prediction_accuracy', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.communityprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SRICalculation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_social_value', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sroi_ratio', models.FloatField(null=True)),
                ('cost_benefit_analysis', models.JSONField(default=dict)),
                ('calculation_methodology', models.TextField()),
                ('evidence_standards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('audit_trail', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sroi', to='impact.intervention')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
