# Generated by Django 6.1 on 2026-08-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('organisation', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('document_type', models.CharField(max_length=50)),
                ('full_citation', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['reference_code'],
            },
        ),
    ]
