# Generated by Django 6.1 on 2026-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_evidencesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproxy',
            name='data_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='evidence_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='evidence_sources',
            field=models.ManyToManyField(blank=True, related_name='proxies', to='impact.evidencesource'),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='geographic_scope',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='unit_of_measure',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
