# Generated by Django 6.1 on 2026-08-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_financialproxy_data_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesource',
            name='evidence_url',
            field=models.URLField(blank=True, help_text='Direct link to evidence source', null=True),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='evidence_url',
            field=models.URLField(blank=True, help_text='Direct link to evidence source', null=True),
        ),
    ]
