# Generated by Django 6.1 on 2026-08-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0004_evidencesource_evidence_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproxy',
            name='evidence_match',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='evidence_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='framework',
            field=models.CharField(choices=[('SCC', 'Surrey County Council'), ('GLOBAL', 'Global/Other Frameworks'), ('TOMS', 'National TOMs Framework'), ('NI', 'Northern Ireland Specific')], default='GLOBAL', max_length=20),
        ),
        migrations.AddField(
            model_name='financialproxy',
            name='research_batch',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
