# Generated by Django 6.1 on 2026-08-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0006_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCSEResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer_typology', models.CharField(max_length=50)),
                ('prevention_level', models.CharField(max_length=50)),
                ('beneficiary_count', models.IntegerField()),
                ('baseline_situation', models.TextField()),
                ('evidence_level', models.CharField(max_length=10)),
                ('deadweight', models.IntegerField()),
                ('attribution', models.IntegerField()),
                ('displacement', models.IntegerField()),
                ('dropoff', models.IntegerField()),
                ('social_value', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
