# Generated by Django 6.1 on 2026-08-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0007_vcseresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(choices=[('scheduled', 'Scheduled Update'), ('query_triggered', 'Query Triggered'), ('manual', 'Manual Search')], max_length=20)),
                ('query_used', models.TextField()),
                ('sources_searched', models.JSONField(default=list)),
                ('items_found', models.IntegerField(default=0)),
                ('items_added', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('academic', 'Academic Research'), ('government', 'Government Report'), ('charity', 'Charity Evaluation'), ('user', 'User Contribution'), ('ai_discovered', 'AI Discovered')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('publisher', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('abstract', models.TextField()),
                ('full_text', models.TextField(blank=True)),
                ('key_findings', models.JSONField(default=list)),
                ('intervention_type', models.CharField(max_length=100)),
                ('target_group', models.CharField(max_length=100)),
                ('outcome_measures', models.JSONField(default=list)),
                ('evidence_quality', models.CharField(choices=[('A', 'A - Strong (RCT, Meta-analysis)'), ('B', 'B - Good (Controlled study)'), ('C', 'C - Moderate (Before/after)'), ('D', 'D - Limited (Case study)')], default='C', max_length=1)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('sample_size', models.IntegerField(blank=True, null=True)),
                ('is_surrey_specific', models.BooleanField(default=False)),
                ('surrey_area', models.CharField(blank=True, max_length=100)),
                ('sroi_ratio', models.CharField(blank=True, max_length=20)),
                ('cost_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('embedding_vector', models.JSONField(default=list)),
                ('extracted_keywords', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('citation_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-confidence_score', '-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('results_found', models.IntegerField()),
                ('user_clicked_results', models.JSONField(default=list)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True)),
                ('results_were_sufficient', models.BooleanField(default=True)),
                ('suggested_new_evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_id', models.CharField(max_length=50, unique=True)),
                ('user_hash', models.CharField(max_length=64)),
                ('project_type', models.CharField(max_length=100)),
                ('intervention_category', models.CharField(max_length=100)),
                ('target_demographic', models.CharField(max_length=100)),
                ('surrey_area', models.CharField(blank=True, max_length=100)),
                ('people_reached', models.IntegerField()),
                ('outcomes_achieved', models.JSONField(default=list)),
                ('sroi_calculated', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('what_worked', models.TextField()),
                ('what_didnt', models.TextField()),
                ('key_lessons', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='impact.evidenceitem')),
            ],
        ),
    ]
