# Generated by Django 6.1 on 2026-08-27 20:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('contact_details', models.JSONField(default=dict)),
                ('is_scc_contractor', models.BooleanField(default=False)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SVCommitment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commitment_reference', models.CharField(max_length=20, unique=True)),
                ('target_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('multiple_disadvantage', 'Multiple Disadvantage'), ('low_uptake_health', 'Low Uptake of Health Services'), ('digital_inclusion', 'Digital Inclusion'), ('transport_barriers', 'Transport Barriers'), ('disability_access', 'Disability Access')], max_length=50), default=list)),
                ('health_inequality_focuses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('description', models.TextField()),
                ('expected_outcomes', models.JSONField(default=list)),
                ('financial_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('required_evidence_standards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('surrey_hwb_alignment', models.BooleanField(default=False)),
                ('nhs_business_recommendation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('NEGOTIATED', 'Negotiated'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('VERIFIED', 'Verified')], default='PROPOSED', max_length=20)),
                ('proposed_date', models.DateField()),
                ('target_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('milestones', models.JSONField(default=list)),
                ('evidence_submitted', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='commitments.supplier')),
            ],
            options={
                'ordering': ['-proposed_date'],
            },
        ),
    ]
