# Generated by Django 6.1 on 2026-08-27 20:17

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('IMAGE', 'Image Upload'), ('TEXT', 'Text Description'), ('VOICE', 'Voice Recording'), ('MIXED', 'Mixed Media')], max_length=10)),
                ('text_content', models.TextField(blank=True)),
                ('media_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list)),
                ('audio_transcript', models.TextField(blank=True)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('extracted_activities', models.JSONField(default=list)),
                ('estimated_impact', models.JSONField(default=dict)),
                ('impact_score', models.FloatField(blank=True, null=True)),
                ('confidence_rating', models.FloatField(blank=True, null=True)),
                ('recommended_actions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list)),
                ('community_context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='communities.communityprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_type', models.CharField(choices=[('PREVENTATIVE', 'Preventative Focus'), ('SVROI', 'Maximum Social Value ROI'), ('MIXED', 'Balanced Approach')], max_length=15)),
                ('budget_constraint', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('priority_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('ai_prompt', models.TextField()),
                ('generated_activities', models.JSONField(default=list)),
                ('predicted_sroi', models.FloatField(null=True)),
                ('expected_preventative_impact', models.FloatField(null=True)),
                ('risk_mitigation_score', models.FloatField(null=True)),
                ('selected_activity', models.JSONField(blank=True, null=True)),
                ('selection_rationale', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_communities', models.ManyToManyField(to='communities.communityprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
