# Generated by Django 6.1 on 2026-08-20 17:27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicalFramework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('framework_type', models.CharField(choices=[('ADVISORY_BOARD', 'Resident Advisory Board'), ('PRIVACY_REVIEW', 'Privacy Impact Assessment'), ('ALGORITHM_AUDIT', 'Algorithm Audit')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resident_representatives', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100))),
                ('meeting_notes', models.JSONField(default=dict)),
                ('approved_recommendations', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('area_type', models.CharField(choices=[('LSOA', 'Lower Layer Super Output Area'), ('MSOA', 'Middle Layer Super Output Area'), ('WARD', 'Electoral Ward'), ('DISTRICT', 'District Council')], max_length=20)),
                ('boundary', models.TextField(blank=True, null=True)),
                ('centroid', models.TextField(blank=True, null=True)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.geographicarea')),
            ],
            options={
                'indexes': [models.Index(fields=['area_type', 'code'], name='core_geogra_area_ty_8b2feb_idx'), models.Index(fields=['embedding'], name='embedding_idx')],
            },
        ),
    ]
