# Generated by Django 6.1 on 2026-08-20 17:27

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_REVIEW', 'Under Review'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('census_data', models.JSONField(default=dict)),
                ('deprivation_index', models.JSONField(default=dict)),
                ('health_outcomes', models.JSONField(default=dict)),
                ('composite_disadvantage_score', models.FloatField(blank=True, null=True)),
                ('health_inequality_index', models.FloatField(blank=True, null=True)),
                ('social_isolation_risk', models.FloatField(blank=True, null=True)),
                ('resident_surveys', models.JSONField(default=list)),
                ('community_reports', models.JSONField(default=list)),
                ('provider_insights', models.JSONField(default=list)),
                ('ai_generated_summary', models.TextField(blank=True)),
                ('emerging_needs_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('early_warning_signals', models.JSONField(default=dict)),
                ('profile_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('geographic_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.geographicarea')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('SURVEY', 'Community Survey'), ('MEETING', 'Public Meeting'), ('DIGITAL', 'Digital Platform'), ('PROVIDER', 'Service Provider Report')], max_length=20)),
                ('source_date', models.DateField()),
                ('raw_text', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('extracted_themes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('priority_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('severity_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('estimated_affected_residents', models.IntegerField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(default=dict)),
                ('community_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='communities.communityprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source_date'],
            },
        ),
        migrations.AddIndex(
            model_name='communityprofile',
            index=models.Index(fields=['composite_disadvantage_score'], name='communities_composi_0ada46_idx'),
        ),
        migrations.AddIndex(
            model_name='communityprofile',
            index=models.Index(fields=['profile_embedding'], name='profile_embedding_idx'),
        ),
    ]
